version: '3.8'

services:

  # =========================
  # PROMETHEUS (METRICS)
  # =========================
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./docker/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"

  # Access:
  # http://localhost:9090
  # No login required
  # Query example: payment_success_total


  # =========================
  # GRAFANA (DASHBOARD)
  # =========================
  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin

  # Access:
  # http://localhost:3000
  # Username: admin
  # Password: admin


  # =========================
  # ZIPKIN (TRACING)
  # =========================
  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    ports:
      - "9411:9411"

  # Access:
  # http://localhost:9411
  # View traces here


  # =========================
  # ELASTICSEARCH (LOG STORAGE)
  # =========================
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.14.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - "9200:9200"

  # Access:
  # http://localhost:9200


  # =========================
  # LOGSTASH (LOG PROCESSING)
  # =========================
  logstash:
    image: docker.elastic.co/logstash/logstash:8.14.0
    container_name: logstash
    volumes:
      - ./docker/logstash/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
    ports:
      - "5001:5000"

  # Receives logs from Spring Boot


  # =========================
  # KIBANA (LOG UI)
  # =========================
  kibana:
    image: docker.elastic.co/kibana/kibana:8.14.0
    container_name: kibana
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200

  # Access:
  # http://localhost:5601